# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f401f0af0dae84106d68a8f90de25aedca628d1c826fa10b5b671074f4e13c7f9e5d738b34e70ddf600392f730811d6d3cd1baea58acde2e19f094f6dd15f3b8

test:
  secret_key_base: dd6dffe3ed17aff464b8929c10791363e55f117d0bf391e3f3a1f7152df36567885f7c4741dc70efaa1bba98de4b6149e7264853aea359eca4ad7b115c59ae17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
